import React, { useMemo, useState } from "react";
import { fetchAllDetectionData } from "@/utils/detectionDataModification";
import { ModifiedDetectionData, ModifiedDetectionDataForSelectedDate } from "../../types/apiResponse/apis";
import DetectionSummaryBox from "@/components/Detection/DetectionSummaryBox";
import DetectionTableUi from "@/components/Detection/DetectionTableUi";
import { parseCookie } from "@/utils/Auth";
import MIN_DATE from "@/utils/minDate";
import Head from "next/head";

export async function getServerSideProps<GetServerSideProps>(context: any) {
  const { AccessToken } = parseCookie(context.req.headers.cookie);

  try {
    let date = context.query.date;
    if (!date) {
      date = new Date().toLocaleDateString("fr-CA");
    }
    const res = await fetchAllDetectionData(AccessToken, date);

    if (res[date]) {
      res[date].data.sort(
        (a: ModifiedDetectionData, b: ModifiedDetectionData) => {
          return b.stats.Epochs - a.stats.Epochs;
        }
      );
    }

    return {
      props: {
        data: res,
        date: date,
      },
    };
  } catch {
    return {
      props: {
        error: "error",
      },
    };
  }
}

function Index({ data, date }: any) {
  const detectionDataForSelectedDate: ModifiedDetectionDataForSelectedDate =
    data[date];
  return (
    <>
      <Head>
        <title>Detection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[896px]">
        <div className="p-4 max-w-[1800px] m-auto flex flex-col  overflow-hidden">
          <div className="flex flex-row justify-between">
            <div className="flex flex-row-reverse pb-5">
              <input
                type="date"
                min={MIN_DATE}
                max={new Date().toLocaleDateString("fr-CA")}
                value={date}
                onChange={(e) => {
                  // setPage(0);
                  window.location.replace(`/detection?date=${e.target.value}`);
                }}
                className="border-none rounded-lg bg-gray-100 "
              />
            </div>
          </div>
          <DetectionSummaryBox
            dateInput={date}
            detectionDataForSelectedDate={detectionDataForSelectedDate}
          />
          <DetectionTableUi
            dateInput={date}
            detectionDataForSelectedDate={detectionDataForSelectedDate}
          />
        </div>
      </main>
    </>
  );
}

export default Index;