import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { getServerSession } from "next-auth/next";
import jwt_decode from "jwt-decode";
import axios from "axios";
import { AlertSummary, OrgNamesApiResponse } from "../types/apiResponse/apis";
import { useState, useMemo, useEffect } from "react";
import { AlertPageProps } from "../types/pageProps/pageProps";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Link from "next/link";
import { getAlertSummary, getOrgName } from "../utils/package/serverSideApiCalls";
import AlertSummaryBox from "@/components/Alerts/AlertSummaryBox";
import AlertTableUi from "@/components/Alerts/AlertTableUi";
import { parseCookie } from "@/utils/Auth";

const NoOfOrgPerPage = 5;

export async function getServerSideProps<GetServerSideProps>(context: any) {

  const { AccessToken } = parseCookie(context.req.headers.cookie);

  try {
    const alertData = await getAlertSummary(AccessToken);
    let data: AlertSummary[] = alertData.data;
    //sort the data in decending order in terms of number of allerts generated in an org
    data.sort((a, b) => {
      return b.Sum > a.Sum ? 1 : -1;
    });
    let set = new Set<string>();
    data.forEach((i) => {
      set.add(i.OrganizationId);
    });
    let url = "";
    set.forEach((i) => {
      url += i + ",";
    });
    const orgNames = await getOrgName(url.slice(0, -1));
    const names: OrgNamesApiResponse[] = orgNames.data;

    let namesMap: any = {};
    names.forEach((name) => {
      namesMap[name.OrganizationId] = name.OrganizationName;
    });

    let finalData = data.map((org) => {
      return { ...org, OrganizationName: namesMap[org.OrganizationId] };
    });

    return {
      props: {
        alertData: finalData,
      },
    };
  } catch {
    return {
      props: {
        alertData: [],
      },
    };
  }
}

export default function Home({ alertData }: AlertPageProps) {
  const [date, setDate] = useState(new Date().toLocaleDateString("fr-CA"));

  const session = useSession();
  const alertDataForSelectedDate = useMemo(() => {
    return alertData.filter((org) => org.Date === date);
  }, [date]);

  //calculate number of alerts in a day
  const totalAlertsInaDay = useMemo(() => {
    const total = alertDataForSelectedDate.reduce((sum, i) => {
      return sum + i.Sum;
    }, 0);
    return total;
  }, [alertDataForSelectedDate]);

  //calculate the number of pages to paginated the data
  return (
    <>
      <Head>
        <title>Alerts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-[896px]">
        <div className="p-4 max-w-[1800px] m-auto flex flex-col  overflow-hidden">
          <div className="flex flex-row justify-between">
            <div className="flex flex-row-reverse pb-5">
              <input
                type="date"
                value={date}
                onChange={(e) => setDate(e.target.value)}
                className="border-none rounded-lg bg-gray-100 "
              />
            </div>
            <h3 className="font-medium p-2">Hello, {session.data?.user.name}</h3>
          </div>
          <AlertSummaryBox
            totalOrgs={alertDataForSelectedDate?.length}
            totalAlertsInaDay={totalAlertsInaDay}
            date={date}
            setDate={setDate}
          />
          <AlertTableUi
            date={date}
            alertDataForSelectedDate={alertDataForSelectedDate}
          />
        </div>
      </main>
    </>

  );
}