import Head from "next/head";
import { useSession } from "next-auth/react";
import Image from "next/image";
import { useEffect, useState } from "react";
import { signOut } from "next-auth/react";
import Link from "next/link";
import { useRouter } from "next/router"
import LeftMenu from "../components/leftMenu"

type LayoutPageProps = {
  children: React.ReactNode;
};

export default function Layout({ children }: LayoutPageProps) {
  const { status, data } = useSession();
  const [title, setTitle] = useState('Alerts');
  const router = useRouter()
  useEffect(() => {
    setTitle(document.title)

  }, [router])

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data && (
          <div>
            <nav className="sticky top-0 bg-blue-theme z-50 shadow-lg p-1 px-2">
              <div className="flex justify-center items-center  ">
                <LeftMenu
                  operatorName={data?.user.name}
                  tabs={[
                    { tabTitle: 'Alerts', tabPath: '/' },
                    { tabTitle: 'Detections', tabPath: '/detection' },
                    { tabTitle: 'Records', tabPath: '/records' }
                  ]} />
                <h2 className="font-medium p-2 text-white">{title}</h2>
                <div className="right-3	absolute">
                  <button
                    className="p-1 border rounded flex justify-center gap-2 cursor-pointer"
                    onClick={() => signOut()}
                  >
                    <span className="font-semibold text-white">Logout</span>
                  </button>
                </div>
              </div>
            </nav>
          </div>
        )}
        <div>{children}</div>
      </main>
    </>
  );
}