name: Build & Deploy

on:
  pull_request:
    types:
      - closed
    branches: [master]
  push:
    branches: [sit]

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Build
        # working-directory: dozee/app
        run: |
          npm install
          CI=false npm run build
          echo github.ref_name

      - name: Build, tag and push branch image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.repository }}
          IMAGE_TAG: ${{ steps.buildgen.outputs.BUILD_ID }}
        # working-directory: dozee/app
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest-${GITHUB_REF##*/} .
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
